### ISSUE TITLE
好像没有这个符号了

### ISSUE THREAD

**Issue by 2833844911** [weblifeio/cronet-go#17]
好像没有这个符号了

/root/go/pkg/mod/github.com/weblifeio/cronet-go@v0.0.0-20240501155250-bdd31ebbf0f7/engine_params.go:227:20: could not determine kind of name for C.Cronet_EngineParams_proxy_server_get
/root/go/pkg/mod/github.com/weblifeio/cronet-go@v0.0.0-20240501155250-bdd31ebbf0f7/engine_params.go:222:2: could not determine kind of name for C.Cronet_EngineParams_proxy_server_set

**Comment by Lucaks** [comment]
> 好像没有这个符号了
> 
> /root/go/pkg/mod/github.com/weblifeio/cronet-go@v0.0.0-20240501155250-bdd31ebbf0f7/engine_params.go:227:20: could not determine kind of name for C.Cronet_EngineParams_proxy_server_get /root/go/pkg/mod/github.com/weblifeio/cronet-go@v0.0.0-20240501155250-bdd31ebbf0f7/engine_params.go:222:2: could not determine kind of name for C.Cronet_EngineParams_proxy_server_set

you should patch chromium。https://github.com/weblifeio/chromium/ develop branch

**Comment by 2833844911** [comment]
好哒我这里已经解决了呢，需要自己实现设置代理这个方法

**Comment by 2833844911** [comment]
好的呢
